### ISSUE TITLE
Misleading instruction?

### ISSUE THREAD

**Issue by Aleadinglight** [vnspoj/vnspoj.github.io#2]
> You'll be required password to install packages. If you get error requiring "Make sure that gem install ...", please execute the command with sudo.

This is what I got from terminal:

> Don't run Bundler as root. Bundler can ask for sudo if it is needed, and
installing your bundle as root will break this application for all non-root
users on this machine.

This is a work-around trick that should not be encouraged.

**Comment by huynhsamha** [comment]
Yes, only for linux or macOS, when we run `bundle`, we dont have to use `sudo`. But when we encounter the error requiring permission as root, you should run the recommended command by the bundler in apostrophe ('command here') with `sudo` permission.
