### ISSUE TITLE
World Cup is on going

### ISSUE THREAD

**Issue by Aleadinglight** [vnspoj/vnspoj.github.io#7]
Hello,

Can we take some moment to gratefully appreciate **the efforts and investments of Russian and footballers around the world** and peacefully enjoy this year World Cup rather than working ourselves to death?

**Comment by huynhsamha** [comment]
Creating issues to remember to fix in the future.
Sub: Chỉ tạo issue để nhớ thui ba. Coi WC xong mới fix chứ  😸😸😸
